---

- hosts: jenkins_server
  become: true

  tasks:

  - name: Install OpenJDK 8
    yum: 
      name: java-1.8.0-openjdk 
      state: latest

  - name: Download Jenkins 
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
      
  - name: restart jenkins systemd service
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

