---
# tasks file for roles/nexus
- hosts: nexus_server
  become: true

  tasks:  

  
  - name: Install OpenJDK 8
    yum: 
      name: java-1.8.0-openjdk 
      state: latest

# download nexus 

  - name: Download nexus
    get_url: 
      url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz" 
      dest: /opt

  - name: Extract nexus archive
    unarchive: 
      src: /opt/nexus-3.45.0-01-unix.tar.gz 
      dest: /opt 
      remote_src: yes

  - name: delete archive file
    file: 
      state: absent 
      path: /opt/nexus-3.45.0-01-unix.tar.gz

  - name: rename nexus folder
    command: mv /opt/nexus-3.45.0-01 /opt/nexus
    ignore_errors: True

  - name: delete old folder
    file: 
      state: absent 
      path: /opt/nexus-3.45.0-01

# set user, permissions, config

  - name: Add nexus user
    user: 
      name: nexus
      append: yes

  - name: set ownership for nexus folder
    file:
      path: "{{ item }}"
      owner: nexus
      group: nexus
    loop:
      - /opt/nexus
      - /opt/sonatype-work
      - /tmp

  - name: run service as nexus user (nexus.rc)
    lineinfile: 
      dest: /opt/nexus/bin/nexus.rc 
      regexp: "#run_as_user=" 
      line: run_as_user="nexus"'


#  - name: Modify memory settings in Nexus configuration file
#    lineinfile: 
#      dest: /opt/nexus/bin/nexus.vmoptions 
#      regexp: "-Xmx2703m" 
#      line: "-Xmx512m"

#  - name: Create symbolic link 
#    file:
#      src: "/opt/nexus/bin/nexus"
#      dest: "/etc/init.d/nexus"
#      state: link

# set nexus as a systemd service and start it

  - name: create systemd service
    copy: 
      src: /Users/apaikush/ansible/jenkins_install/playbook/nexus.service
      dest: /etc/systemd/system/nexus.service

  - name: reload systemctl and start nexus
    systemd:
      name: nexus.service
      daemon_reload: yes
      enabled: yes
      state: started